<?php

use Illuminate\Database\Seeder;

class DetailProsedurTableDataSeeder extends Seeder
{
	use DisableForeignKeys;
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$this->disableForeignKeys();
    	DB::table('sop_detail')->truncate();

		DB::table('sop_detail')->insert([
			['id' => '1', 'kode' => 'DP_0101_001', 'keterangan' => 'Menerima Reservasi dan menjawab sesuai permintaan dengan melihat Tabel  RESERVATION CHART ', 'id_sop' => '1', 'no_urut' => '1', ],
			['id' => '2', 'kode' => 'DP_0101_002', 'keterangan' => 'Memasukkan data reservasi ke system (tipe kamar, lama menginap, special request tamu, antar / jemput)', 'id_sop' => '1', 'no_urut' => '2', ],
			['id' => '3', 'kode' => 'DP_0102_001', 'keterangan' => 'Mengunakan Telephone Manner  ETIKA  BERTELPON ', 'id_sop' => '2', 'no_urut' => '3', ],
			['id' => '4', 'kode' => 'DP_0102_002', 'keterangan' => 'Menanyakan nama lengkap tamu', 'id_sop' => '2', 'no_urut' => '4', ],
			['id' => '5', 'kode' => 'DP_0102_003', 'keterangan' => 'Menanyakan tipe kamar dan berapa lama akan menginap', 'id_sop' => '2', 'no_urut' => '5', ],
			['id' => '6', 'kode' => 'DP_0102_004', 'keterangan' => 'Memberitahukan harga kamar kepada tamu', 'id_sop' => '2', 'no_urut' => '6', ],
			['id' => '7', 'kode' => 'DP_0102_005', 'keterangan' => 'Minta no telepon tamu dan no kartu kredit tamu sbg jaminan', 'id_sop' => '2', 'no_urut' => '7', ],
			['id' => '8', 'kode' => 'DP_0102_006', 'keterangan' => 'Menjelaskan ke tamu tentang prosedur reservasi dan prosedur pembatalan reservasi  secara lengkap dan benar.', 'id_sop' => '2', 'no_urut' => '8', ],
			['id' => '9', 'kode' => 'DP_0102_007', 'keterangan' => 'Menutup pembicaraan telepon dengan salam dan ucapan terima kasih, tak lupa menyebutkan nama tamu tersebut.', 'id_sop' => '2', 'no_urut' => '9', ],
			['id' => '10', 'kode' => 'DP_0102_008', 'keterangan' => 'Menuliskan detail di formulir reservasi, input ke system, dan file sesuai tanggal dan bulannya. (tipe kamar, lama menginap, special request tamu, antar / jemput)', 'id_sop' => '2', 'no_urut' => '10', ],
			['id' => '11', 'kode' => 'DP_0201_001', 'keterangan' => 'Cetak Daftar Tamu yang harus dijemput 1 hari sebelum tanggal penjemputan, dan cek ulang pada hari tsb', 'id_sop' => '3', 'no_urut' => '11', ],
			['id' => '12', 'kode' => 'DP_0201_002', 'keterangan' => 'Pastikan jumlah mobil dan kapasitas tiap mobil sesuai dengan jumlah tamu', 'id_sop' => '3', 'no_urut' => '12', ],
			['id' => '13', 'kode' => 'DP_0201_003', 'keterangan' => 'Pastikan kelengkapan mobil, sebaiknya menggunakan checklist', 'id_sop' => '3', 'no_urut' => '13', ],
			['id' => '14', 'kode' => 'DP_0201_004', 'keterangan' => 'Bila diperlukan, membawa papan bertulis nama tamu, perhatikan penulisan nama tamu', 'id_sop' => '3', 'no_urut' => '14', ],
			['id' => '15', 'kode' => 'DP_0201_005', 'keterangan' => 'Bisa disediakan koran, minuman dingin, handuk basah, pilihan musik', 'id_sop' => '3', 'no_urut' => '15', ],
			['id' => '16', 'kode' => 'DP_0201_006', 'keterangan' => 'Usahakan untuk tiba di lokasi penjemputan minimal 30 menit sebelum tamu tiba', 'id_sop' => '3', 'no_urut' => '16', ],
			['id' => '17', 'kode' => 'DP_0201_007', 'keterangan' => 'Pastikan Supir yang akan menjemput sudah dibekali dengan tata cara memperlakukan tamu dengan baik', 'id_sop' => '3', 'no_urut' => '17', ],
			['id' => '18', 'kode' => 'DP_0201_008', 'keterangan' => 'Sopir yg menjemput tamu berpenampilan rapi, bersih, tidak bau badan', 'id_sop' => '3', 'no_urut' => '18', ],
			['id' => '19', 'kode' => 'DP_0201_009', 'keterangan' => 'Sopir yg menjemput tamu sikap tubuh dan cara bicara sopan, ramah', 'id_sop' => '3', 'no_urut' => '19', ],
			['id' => '20', 'kode' => 'DP_0201_010', 'keterangan' => 'Membantu bawakan koper tamu secara berhati-hati, konfirmasikan pada tamu jumlah koper / barang bawaannya', 'id_sop' => '3', 'no_urut' => '20', ],
			['id' => '21', 'kode' => 'DP_0201_011', 'keterangan' => 'Membukakan pintu mobil saat tamu akan masuk / keluar mobil, tamu perempuan lebih dahulu', 'id_sop' => '3', 'no_urut' => '21', ],
			['id' => '22', 'kode' => 'DP_0201_012', 'keterangan' => 'Berhati-hati saat menutup pintu mobil, tidak dibanting', 'id_sop' => '3', 'no_urut' => '22', ],
			['id' => '23', 'kode' => 'DP_0201_013', 'keterangan' => 'Sopir berbicara hanya jika tamu yg mengajak berbicara, kecuali pada saat mengingatkan untuk', 'id_sop' => '3', 'no_urut' => '23', ],
			['id' => '24', 'kode' => 'DP_0201_014', 'keterangan' => 'Memakai sabuk pengaman, menawarkan minuman, handuk basah, koran, musik. ', 'id_sop' => '3', 'no_urut' => '24', ],
			['id' => '25', 'kode' => 'DP_0201_015', 'keterangan' => 'Menyampaikan terimakasih dan salam saat akan meninggalkan tamu', 'id_sop' => '3', 'no_urut' => '25', ],
			['id' => '26', 'kode' => 'DP_0201_016', 'keterangan' => 'Teleponlah hotel anda untuk menyampaikan perkiraan berapa menit lagi tamu akan tiba', 'id_sop' => '3', 'no_urut' => '26', ],
			['id' => '27', 'kode' => 'DP_0201_017', 'keterangan' => 'Hentikan mobil tepat di jalan masuk hotel', 'id_sop' => '3', 'no_urut' => '27', ],
			['id' => '28', 'kode' => 'DP_0201_018', 'keterangan' => 'Penjaga pintu hotel (doorman / bell boy) siap di jalan masuk, dan memberi salam selamat datang', 'id_sop' => '3', 'no_urut' => '28', ],
			['id' => '29', 'kode' => 'DP_0201_019', 'keterangan' => 'Jika mobil sewa, supir minta tanda tangan pada nota, atau minta pembayaran tunai', 'id_sop' => '3', 'no_urut' => '29', ],
			['id' => '30', 'kode' => 'DP_0301_001', 'keterangan' => 'Memeriksa ketersediaan kamar agar tidak terjadi Double Booking,', 'id_sop' => '4', 'no_urut' => '30', ],
			['id' => '31', 'kode' => 'DP_0301_002', 'keterangan' => 'Jika tidak ada kamar yang tersedia, jelaskan pada tamu dengan sopan, disertai permohonan maaf', 'id_sop' => '4', 'no_urut' => '31', ],
			['id' => '32', 'kode' => 'DP_0301_003', 'keterangan' => 'Jika ada kamar kosong yang sesuai dengan keinginan tamu, minta ID Tamu untuk melakukan Registrasi.', 'id_sop' => '4', 'no_urut' => '32', ],
			['id' => '33', 'kode' => 'DP_0301_004', 'keterangan' => 'Copy ID tamu, lalu kembalikan', 'id_sop' => '4', 'no_urut' => '33', ],
			['id' => '34', 'kode' => 'DP_0301_005', 'keterangan' => 'Menuliskan detail di formulir reservasi, input ke system, dan file sesuai tanggal dan bulannya. (tipe kamar, lama menginap, special request tamu, antar / jemput)', 'id_sop' => '4', 'no_urut' => '34', ],
			['id' => '35', 'kode' => 'DP_0301_006', 'keterangan' => 'Mengecek kesiapan kamar beserta fasilitas dan komplimennya', 'id_sop' => '4', 'no_urut' => '35', ],
			['id' => '36', 'kode' => 'DP_0301_007', 'keterangan' => 'Jika ada kebijakan hotel mengenai Deposit, maka mintalah Deposit ', 'id_sop' => '4', 'no_urut' => '36', ],
			['id' => '37', 'kode' => 'DP_0301_008', 'keterangan' => 'Mempersilakan tamu untuk duduk', 'id_sop' => '4', 'no_urut' => '37', ],
			['id' => '38', 'kode' => 'DP_0301_009', 'keterangan' => 'Menyuguhkan cold towel dan welcome drink', 'id_sop' => '4', 'no_urut' => '38', ],
			['id' => '39', 'kode' => 'DP_0301_010', 'keterangan' => 'Menjelaskan service dan fasilitas hotel kepada tamu', 'id_sop' => '4', 'no_urut' => '39', ],
			['id' => '40', 'kode' => 'DP_0301_011', 'keterangan' => 'Menjelaskan waktu breakfast dan afternoon tea kepada tamu', 'id_sop' => '4', 'no_urut' => '40', ],
			['id' => '41', 'kode' => 'DP_0301_012', 'keterangan' => 'Mempersilahkan kepada tamu untuk mengisi formulir registrasi dengan lengkap.', 'id_sop' => '4', 'no_urut' => '41', ],
			['id' => '42', 'kode' => 'DP_0301_013', 'keterangan' => 'Tamu dan Resepsionis harus menanda-tangani formulir registrasi yang telah lengkap diisi.', 'id_sop' => '4', 'no_urut' => '42', ],
			['id' => '43', 'kode' => 'DP_0301_014', 'keterangan' => 'Menyimpan registrasi tamu di file Front Office sesuai dengan nomor kamar.', 'id_sop' => '4', 'no_urut' => '43', ],
			['id' => '44', 'kode' => 'DP_0301_015', 'keterangan' => 'Mempersilahkan dan mengantar tamu ke kamar.', 'id_sop' => '4', 'no_urut' => '44', ],
			['id' => '45', 'kode' => 'DP_0301_016', 'keterangan' => 'Membawa tas dan koper tamu ke kamar', 'id_sop' => '4', 'no_urut' => '45', ],
			['id' => '46', 'kode' => 'DP_0302_001', 'keterangan' => 'Menyiapkan data tamu yang sudah reservasi untuk hari tersebut', 'id_sop' => '5', 'no_urut' => '46', ],
			['id' => '47', 'kode' => 'DP_0302_002', 'keterangan' => 'Mengecek kesiapan kamar beserta fasilitas dam komplimennya', 'id_sop' => '5', 'no_urut' => '47', ],
			['id' => '48', 'kode' => 'DP_0302_003', 'keterangan' => 'Menyiapkan welcome letter bertanda-tangan General Manager, dan meletakkannya di meja tulis kamar ybs', 'id_sop' => '5', 'no_urut' => '48', ],
			['id' => '49', 'kode' => 'DP_0302_004', 'keterangan' => 'Siapkan semua data dan kelengkapan reservasi dan registrasi yang dibutuhkan', 'id_sop' => '5', 'no_urut' => '49', ],
			['id' => '50', 'kode' => 'DP_0302_005', 'keterangan' => 'Memeriksa kelengkapan amenities (sandal, tissue, shampoo, sabun, conditioner, dll sesuai standar)', 'id_sop' => '5', 'no_urut' => '50', ],
			['id' => '51', 'kode' => 'DP_0302_006', 'keterangan' => 'Apabila Villa menyediakan makanan / minuman, harus diperiksa apakah masih layak dikonsumsi', 'id_sop' => '5', 'no_urut' => '51', ],
			['id' => '52', 'kode' => 'DP_0302_007', 'keterangan' => 'Menyiapkan cold towel, welcome drink, kunci kamar ybs', 'id_sop' => '5', 'no_urut' => '52', ],
			['id' => '53', 'kode' => 'DP_0302_008', 'keterangan' => 'Menyiapkan porter untuk menyambut tamu', 'id_sop' => '5', 'no_urut' => '53', ],
			['id' => '54', 'kode' => 'DP_0302_009', 'keterangan' => 'Mengucapkan selamat datang, membawakan koper tamu ke lobby', 'id_sop' => '5', 'no_urut' => '54', ],
			['id' => '55', 'kode' => 'DP_0302_010', 'keterangan' => 'Jika ada kebijakan hotel mengenai Deposit, maka mintalah Deposit ', 'id_sop' => '5', 'no_urut' => '55', ],
			['id' => '56', 'kode' => 'DP_0302_011', 'keterangan' => 'Mempersilakan tamu untuk duduk', 'id_sop' => '5', 'no_urut' => '56', ],
			['id' => '57', 'kode' => 'DP_0302_012', 'keterangan' => 'Menyuguhkan cold towel dan welcome drink', 'id_sop' => '5', 'no_urut' => '57', ],
			['id' => '58', 'kode' => 'DP_0302_013', 'keterangan' => 'Menjelaskan service dan fasilitas hotel kepada tamu', 'id_sop' => '5', 'no_urut' => '58', ],
			['id' => '59', 'kode' => 'DP_0302_014', 'keterangan' => 'Menjelaskan waktu breakfast dan afternoon tea kepada tamu', 'id_sop' => '5', 'no_urut' => '59', ],
			['id' => '60', 'kode' => 'DP_0302_015', 'keterangan' => 'Mempersilahkan kepada tamu untuk mengisi formulir registrasi dengan lengkap.', 'id_sop' => '5', 'no_urut' => '60', ],
			['id' => '61', 'kode' => 'DP_0302_016', 'keterangan' => 'Tamu dan Resepsionis harus menanda-tangani formulir registrasi yang telah lengkap diisi.', 'id_sop' => '5', 'no_urut' => '61', ],
			['id' => '62', 'kode' => 'DP_0302_017', 'keterangan' => 'Menyimpan registrasi tamu di file Front Office sesuai dengan nomor kamar.', 'id_sop' => '5', 'no_urut' => '62', ],
			['id' => '63', 'kode' => 'DP_0302_018', 'keterangan' => 'Mempersilahkan dan mengantar tamu ke kamar.', 'id_sop' => '5', 'no_urut' => '63', ],
			['id' => '64', 'kode' => 'DP_0302_019', 'keterangan' => 'Membawa tas dan koper tamu ke kamar', 'id_sop' => '5', 'no_urut' => '64', ],
			['id' => '65', 'kode' => 'DP_0401_001', 'keterangan' => 'Saat closing malam hari masing2 bagian memasukkan tagihan2 tamu ( café , laundry , dll )', 'id_sop' => '6', 'no_urut' => '65', ],
			['id' => '66', 'kode' => 'DP_0401_002', 'keterangan' => 'Saat closing malam hari atau pagi hari sebelum waktu check out, cetak semua tagihan tamu yang akan check out esok hari, pastikan hasil cetak tagihan tsb benar , masukkan tagihan2 tersebut dalam folder tamu yang akan check out. ', 'id_sop' => '6', 'no_urut' => '66', ],
			['id' => '67', 'kode' => 'DP_0401_003', 'keterangan' => 'Petugas front office menelpon bagian house keeping untuk memberikan informasi bahwa kamar no sekian akan check out', 'id_sop' => '6', 'no_urut' => '67', ],
			['id' => '68', 'kode' => 'DP_0401_004', 'keterangan' => 'Petugas house keeping memeriksa kamar apakah ada barang tamu yang tertinggal atau ada fasilitas hotel yang terbawa', 'id_sop' => '6', 'no_urut' => '68', ],
			['id' => '69', 'kode' => 'DP_0401_005', 'keterangan' => 'Petugas front office menelpon bagian restaurant / laundry dll untuk memastikan tidak ada tagihan yang tertinggal tsb.', 'id_sop' => '6', 'no_urut' => '69', ],
			['id' => '70', 'kode' => 'DP_0401_006', 'keterangan' => 'Jika ada tagihan yang tertinggal, petugas lebih dulu memasukkan tagihan  yang tertinggal tersebut. ', 'id_sop' => '6', 'no_urut' => '70', ],
			['id' => '71', 'kode' => 'DP_0401_007', 'keterangan' => 'Jika nota – nota akan dilunasi seluruhnya, tamu dipersilahkan membayar kekurangan pembayaran / mengambil pengembalian kelebihan deposit', 'id_sop' => '6', 'no_urut' => '71', ],
			['id' => '72', 'kode' => 'DP_0401_008', 'keterangan' => 'Jika nota-nota dilunasi, nota2 dan bukti pelunasan dicetak rangkap 2, ditandatangani oleh kasir dan tamu, yang asli diserahkan kepada tamu, copynya disimpan dalam folder tamu yang sudah check out sebagai arsip', 'id_sop' => '6', 'no_urut' => '72', ],
			['id' => '73', 'kode' => 'DP_0401_009', 'keterangan' => ' jika pembayaran di tagihkan ke pihak lain (misalnya oleh perusahaan yang bekerjasama dengan hotel). Nota2 dicetak rangkap 3, ditandatangani oleh kasir dan tamu, lembar ke 3 diserahkan kepada tamu yang asli diserahkan nantinya digunakan untuk penagihan ke perusahaan penjamin, lembar ke 2 disimpan dalam folder tamu yang sudah check out sebagai arsip', 'id_sop' => '6', 'no_urut' => '73', ],
			['id' => '74', 'kode' => 'DP_0401_010', 'keterangan' => 'Proses check outkan tamu di system', 'id_sop' => '6', 'no_urut' => '74', ],
			['id' => '75', 'kode' => 'DP_0501_001', 'keterangan' => 'Cetak Daftar Tamu yang harus diantar 1 hari sebelum tanggal pengantaran, dan cek ulang pada hari tsb', 'id_sop' => '7', 'no_urut' => '75', ],
			['id' => '76', 'kode' => 'DP_0501_002', 'keterangan' => 'Pastikan jumlah mobil dan kapasitas tiap mobil sesuai dengan jumlah tamu', 'id_sop' => '7', 'no_urut' => '76', ],
			['id' => '77', 'kode' => 'DP_0501_003', 'keterangan' => 'Pastikan kelengkapan mobil, sebaiknya menggunakan checklist', 'id_sop' => '7', 'no_urut' => '77', ],
			['id' => '78', 'kode' => 'DP_0501_004', 'keterangan' => 'Bisa disediakan koran, minuman dingin, handuk basah, pilihan musik', 'id_sop' => '7', 'no_urut' => '78', ],
			['id' => '79', 'kode' => 'DP_0501_005', 'keterangan' => 'Pastikan supir mengetahui tempat tujuan tamu, termasuk terminal keberangkatan tamu', 'id_sop' => '7', 'no_urut' => '79', ],
			['id' => '80', 'kode' => 'DP_0501_006', 'keterangan' => 'Usahakan mobil tiba di lobby hotel, sebelum tamu menunggu, dan tiba di tujuan, 5 - 10 menit lebih cepat dari rencana waktu tiba ', 'id_sop' => '7', 'no_urut' => '80', ],
			['id' => '81', 'kode' => 'DP_0501_007', 'keterangan' => 'Pastikan Supir yang akan mengantar sudah dibekali dengan tata cara memperlakukan tamu dengan baik', 'id_sop' => '7', 'no_urut' => '81', ],
			['id' => '82', 'kode' => 'DP_0501_008', 'keterangan' => 'Sopir yg mengantar tamu berpenampilan rapi, bersih, tidak bau badan', 'id_sop' => '7', 'no_urut' => '82', ],
			['id' => '83', 'kode' => 'DP_0501_009', 'keterangan' => 'Sopir sikap tubuh dan cara bicara sopan, ramah, berbicara jelas, kontak mata jika berbicara', 'id_sop' => '7', 'no_urut' => '83', ],
			['id' => '84', 'kode' => 'DP_0501_010', 'keterangan' => 'Membantu membawakan koper tamu secara berhati-hati, konfirmasikan pada tamu jumlah koper / barang bawaannya', 'id_sop' => '7', 'no_urut' => '84', ],
			['id' => '85', 'kode' => 'DP_0501_011', 'keterangan' => 'Membukakan pintu mobil saat tamu akan masuk / keluar mobil, tamu perempuan lebih dahulu', 'id_sop' => '7', 'no_urut' => '85', ],
			['id' => '86', 'kode' => 'DP_0501_012', 'keterangan' => 'Berhati-hati saat menutup pintu mobil, tidak dibanting', 'id_sop' => '7', 'no_urut' => '86', ],
			['id' => '87', 'kode' => 'DP_0501_013', 'keterangan' => 'Supir berbicara hanya jika tamu yg mengajak berbicara, kecuali pada saat mengingatkan untuk', 'id_sop' => '7', 'no_urut' => '87', ],
			['id' => '88', 'kode' => 'DP_0501_014', 'keterangan' => 'Memakai sabuk pengaman, menawarkan minuman, handuk basah, koran, musik. ', 'id_sop' => '7', 'no_urut' => '88', ],
			['id' => '89', 'kode' => 'DP_0501_015', 'keterangan' => 'Menyampaikan terimakasih dan salam saat akan meninggalkan tamu', 'id_sop' => '7', 'no_urut' => '89', ],
			['id' => '90', 'kode' => 'DP_0501_016', 'keterangan' => 'Jika mobil sewa, sebaiknya mencatat km sebelum dan sesudah berangkat', 'id_sop' => '7', 'no_urut' => '90', ],
			['id' => '91', 'kode' => 'DP_0501_017', 'keterangan' => 'Hentikan mobil sedekat mungkin dengan di jalan masuk bandara / stasiun / lainnya', 'id_sop' => '7', 'no_urut' => '91', ],
			['id' => '92', 'kode' => 'DP_0501_018', 'keterangan' => 'Sekitar 10-15 menit sebelum tiba di tujuan, sampaikan pada tamu bahwa tamu sudah hampir tiba di tujuan', 'id_sop' => '7', 'no_urut' => '92', ],
			['id' => '93', 'kode' => 'DP_0501_019', 'keterangan' => 'Saat tiba di tujuan, sampaikan pada tamu bahwa tamu sudah tiba di tujuan. ', 'id_sop' => '7', 'no_urut' => '93', ],
			['id' => '94', 'kode' => 'DP_0501_020', 'keterangan' => 'Bantu tamu menurunkan koper / barang bawaannya, konfirmasi jumlahnya', 'id_sop' => '7', 'no_urut' => '94', ],
			['id' => '95', 'kode' => 'DP_0501_021', 'keterangan' => 'Sampaikan terimakasih dan salam perpisahan', 'id_sop' => '7', 'no_urut' => '95', ],
			['id' => '96', 'kode' => 'DP_0601_001', 'keterangan' => 'Memeriksa kebersihan seluruh area ', 'id_sop' => '8', 'no_urut' => '96', ],
			['id' => '97', 'kode' => 'DP_0601_002', 'keterangan' => 'Memeriksa kebocoran A/C, kamar mandi, dapur, plafon, dll', 'id_sop' => '8', 'no_urut' => '97', ],
			['id' => '98', 'kode' => 'DP_0601_003', 'keterangan' => 'Memeriksa penyumbatan saluran2 air kamar mandi, dapur, wastafel, dll', 'id_sop' => '8', 'no_urut' => '98', ],
			['id' => '99', 'kode' => 'DP_0601_004', 'keterangan' => 'Memeriksa apakah area segar / tidak berbau', 'id_sop' => '8', 'no_urut' => '99', ],
			['id' => '100', 'kode' => 'DP_0601_005', 'keterangan' => 'Memeriksa kaca adakah yang pecah', 'id_sop' => '8', 'no_urut' => '100', ],
			['id' => '101', 'kode' => 'DP_0601_006', 'keterangan' => 'Memeriksa dinding, plafon, lantai apakah ada yang lembab atau perlu pengecatan', 'id_sop' => '8', 'no_urut' => '101', ],
			['id' => '102', 'kode' => 'DP_0601_007', 'keterangan' => 'Memeriksa apakah alat2 elektronik (AC / TV / dll) berfungsi dengan baik', 'id_sop' => '8', 'no_urut' => '102', ],
			['id' => '103', 'kode' => 'DP_0601_008', 'keterangan' => 'Memeriksa apakah gorden, karpet, dll ada yang perlu diservis / diganti', 'id_sop' => '8', 'no_urut' => '103', ],
			['id' => '104', 'kode' => 'DP_0601_009', 'keterangan' => 'Memeriksa apakah mebel2 ada yang perlu diservis atau ganti, dsb', 'id_sop' => '8', 'no_urut' => '104', ],
			['id' => '105', 'kode' => 'DP_0601_010', 'keterangan' => 'Sebaiknya gunakan check list untuk semua pemeriksaan, agar tidak ada yang terlewat', 'id_sop' => '8', 'no_urut' => '105', ],
			['id' => '106', 'kode' => 'DP_0601_011', 'keterangan' => 'Setiap beberapa waktu perlu pemeriksaan oleh GM', 'id_sop' => '8', 'no_urut' => '106', ],
			['id' => '107', 'kode' => 'DP_0601_012', 'keterangan' => 'Memeriksa tanaman hias dan rumput', 'id_sop' => '8', 'no_urut' => '107', ],
			['id' => '108', 'kode' => 'DP_0602_001', 'keterangan' => 'Memberitahu bagian-bagian lain tentang waktu pest control akan dilakukan untuk tindakan pengamanan', 'id_sop' => '9', 'no_urut' => '108', ],
			['id' => '109', 'kode' => 'DP_0602_002', 'keterangan' => 'Staf House Keeping memandu petugas Pest Control', 'id_sop' => '9', 'no_urut' => '109', ],
			['id' => '110', 'kode' => 'DP_0602_003', 'keterangan' => 'Staf House Keeping mencatat rincian di buku Log Pengendalian hama yang isinya :', 'id_sop' => '9', 'no_urut' => '110', ],
			['id' => '111', 'kode' => 'DP_0602_004', 'keterangan' => 'Manajer akan memeriksa Buku Log Pengendalian Hama setiap minggu untuk memastikan perawatan dilakukan dengan benar', 'id_sop' => '9', 'no_urut' => '111', ],
			['id' => '112', 'kode' => 'DP_0602_005', 'keterangan' => 'Jika ditemukan semut kecoa, tikus, serangga lain, dsb, harus segera dilakukan Pest Control segera, meskipun di luar jadwal rutin', 'id_sop' => '9', 'no_urut' => '112', ],
			['id' => '113', 'kode' => 'DP_0701_001', 'keterangan' => 'Petugas Housekeeping yang mengambil linen dari kamar / tamu memastikan linen yang diterima sesuai jenis dan jumlahnya dengan form Laundry yang diisi tamu. Form Laundry ini menjadi pegangan apabila ada claim dari tamu', 'id_sop' => '10', 'no_urut' => '113', ],
			['id' => '114', 'kode' => 'DP_0701_002', 'keterangan' => 'Beri catatan khusus apabila ada cacat atau tanda khusus pada bahan', 'id_sop' => '10', 'no_urut' => '114', ],
			['id' => '115', 'kode' => 'DP_0701_003', 'keterangan' => 'Petugas bagian Laundry memastikan semua linen yang diterima (dari tamu / dari bagian lain) sesuai dengan jumlah dan jenis item yang tertera pada form Laundry ', 'id_sop' => '10', 'no_urut' => '115', ],
			['id' => '116', 'kode' => 'DP_0701_004', 'keterangan' => 'Beri tanda pada setiap barang sesuai pemiliknya (identitas kamar atau bagian pemilik linen)', 'id_sop' => '10', 'no_urut' => '116', ],
			['id' => '117', 'kode' => 'DP_0701_005', 'keterangan' => 'Pisahkan bahan yang berwarna untuk menghindari luntur. Pisahkan juga bahan putih apabila dibutuhkan pemutih', 'id_sop' => '10', 'no_urut' => '117', ],
			['id' => '118', 'kode' => 'DP_0701_006', 'keterangan' => 'Buat Daftar Laundry untuk dikirim ke Jasa Laundry Luar, lengkap dengan catatan tentang permintaan2 khusus', 'id_sop' => '10', 'no_urut' => '118', ],
			['id' => '119', 'kode' => 'DP_0701_007', 'keterangan' => 'Ambil linen di Laundry Luar sesuai tanggal selesai', 'id_sop' => '10', 'no_urut' => '119', ],
			['id' => '120', 'kode' => 'DP_0701_008', 'keterangan' => 'Atur linen sesuai pemiliknya (tamu / kamar / bagian lain)', 'id_sop' => '10', 'no_urut' => '120', ],
			['id' => '121', 'kode' => 'DP_0701_009', 'keterangan' => 'Distribusikan linen ke kamar / tamu / bagian lain, sebisa mungkin ada tanda tangan penerima', 'id_sop' => '10', 'no_urut' => '121', ],
			['id' => '122', 'kode' => 'DP_0801_001', 'keterangan' => 'Memastikan bangunan dan fasilitas memenuhi keamanan sesuai standar USV', 'id_sop' => '11', 'no_urut' => '122', ],
			['id' => '123', 'kode' => 'DP_0801_002', 'keterangan' => 'Memastikan penampilan tampak luar bangunan dan fasilitas sesuai standar USV', 'id_sop' => '11', 'no_urut' => '123', ],
			['id' => '124', 'kode' => 'DP_0801_003', 'keterangan' => 'Memastikan penampilan penunjang2 (mekanikal & elektrikal) bangunan dan fasilitas sesuai standar USV', 'id_sop' => '11', 'no_urut' => '124', ],
			['id' => '125', 'kode' => 'DP_0801_004', 'keterangan' => 'Memastikan bangunan dan fasilitas memenuhi kenyamanan sesuai standar USV', 'id_sop' => '11', 'no_urut' => '125', ],
			['id' => '126', 'kode' => 'DP_0802_001', 'keterangan' => 'Pembersihan AC setiap 4 bulan', 'id_sop' => '12', 'no_urut' => '126', ],
			['id' => '127', 'kode' => 'DP_0803_001', 'keterangan' => 'Pengecatan dinding luar', 'id_sop' => '13', 'no_urut' => '127', ],
			['id' => '128', 'kode' => 'DP_0804_001', 'keterangan' => 'Pengecatan interior', 'id_sop' => '14', 'no_urut' => '128', ],
			['id' => '129', 'kode' => 'DP_0901_001', 'keterangan' => 'Tindakan preventif mencegah terjadinya bahaya', 'id_sop' => '15', 'no_urut' => '129', ],
			['id' => '130', 'kode' => 'DP_0901_002', 'keterangan' => 'Laporkan kepada yg berwenang', 'id_sop' => '15', 'no_urut' => '130', ],
			['id' => '131', 'kode' => 'DP_0901_003', 'keterangan' => 'Perbaikan permanen disetujui', 'id_sop' => '15', 'no_urut' => '131', ],
			['id' => '132', 'kode' => 'DP_0901_004', 'keterangan' => 'Perbaikan permanen dilaksanakan', 'id_sop' => '15', 'no_urut' => '132', ],
			['id' => '133', 'kode' => 'DP_0902_001', 'keterangan' => 'Laporkan kepada yang berwenang segera', 'id_sop' => '16', 'no_urut' => '133', ],
			['id' => '134', 'kode' => 'DP_0902_002', 'keterangan' => 'Perbaikan permanen disetujui', 'id_sop' => '16', 'no_urut' => '134', ],
			['id' => '135', 'kode' => 'DP_0902_003', 'keterangan' => 'Perbaikan permanen dilaksanakan', 'id_sop' => '16', 'no_urut' => '135', ],
			['id' => '136', 'kode' => 'DP_0903_001', 'keterangan' => 'Usulkan perbaikan dibuat bersamaan dengan anggaran', 'id_sop' => '17', 'no_urut' => '136', ],
			['id' => '137', 'kode' => 'DP_0903_002', 'keterangan' => 'Persetujuan Perbaikan', 'id_sop' => '17', 'no_urut' => '137', ],
			['id' => '138', 'kode' => 'DP_0903_003', 'keterangan' => 'Pelaksanaan Perbaikan', 'id_sop' => '17', 'no_urut' => '138', ],
		]);

        $this->enableForeignKeys();
        //
    }
}
